/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ga_2022;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        //App classUnderTest = new App();
        //assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test
    void testWriteDataLine() {
        App classUnderTest = new App();
        String[] test = {"1","2"};
        classUnderTest.writeDataLine(test);
    }
}
